### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by dimdimich** [swissup/module-theme-editor-swissup-absolute#1]
Hi,

for some reason we already have package 1.1.2 at Marketplace. So i can't submit new verison. Can you please create 1.1.3 ?

**Comment by vovayatsyuk** [comment]
How is it possible? We've just created this module. It had another name previously.

**Comment by vovayatsyuk** [comment]
I see that this module is already uploaded to marketplace, so I'm closing this ticket.

![image](https://user-images.githubusercontent.com/306080/46273499-68c2e180-c55e-11e8-9ab9-a062330e396d.png)

**Comment by dimdimich** [comment]
Sorry i opened ticket in wrong module.
